version: "3.1"

services:
  bot:
    container_name: pizzabot
    image: ghcr.io/coolepizza/pizzabot:master
    networks:
      - pizzabot
    env_file:
      - .env
  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - db_data:/data/db
    networks:
      - pizzabot

networks:
  pizzabot:
    external: false

volumes:
  db_data:
